meineWohnung <- tabItem(tabName = "meineWohnung",
                        sliderInput("mW_qm",
                                    "Quadratmeter:",
                                    min = 0,
                                    max = 40,
                                    value = 0),
                        sliderInput("mW_preis",
                                    "Wohnungspreis:",
                                    min = 0,
                                    max = 600,
                                    value = 0,
                                    step = 5),
                        textOutput("mW_qmpreis"),
                        plotOutput("mW_Hist"))